#!/bin/sh

# PROVIDE: smartdc

. /etc/rc.subr

name="smartdc"
stop_cmd=":"

(/lib/smartdc/set-root-authorized-keys)
if [ ! -f /lib/smartdc/.firstboot-complete-do-not-delete ] ; then
  (/lib/smartdc/firstboot)
fi
(/lib/smartdc/run-operator-script)
(/lib/smartdc/run-user-script)
