#! /bin/bash

# removes unused kernels for Ubuntu only systems

# load common functions
. /lib/smartdc/lib_smartdc_scripts.cfg

ubuntu_remove_unused_kernels() {

  which apt-mark >/dev/null 2>&1 || lib_smartdc_fatal "apt-mark not found"
  which dpkg >/dev/null 2>&1 || lib_smartdc_fatal "dpkg not found"
  UNUSED_KERNELS=$(dpkg --get-selections | grep joyent | grep linux | grep -v `uname -r`)

  for f in $UNUSED_KERNELS
  do
     if [ $f != 'install' ]; then
        echo -n "Purging unused kernel $f (Y\n)" 
        read REPLY
        if [[ $REPLY =~ ^[Yy]$ ]]; then
           apt-mark unhold $f
           out=$(apt-get -y purge $f)
           echo "   - $out"
        else
           echo "Marking curent package as hold"
           apt-mark hold $f
        fi
     fi

  done
}

# Start of Main
# removes unused kernels for Ubuntu only systems
ubuntu_remove_unused_kernels

exit 0
