#! /usr/local/bin/bash
#
# Copyright (c) 2013 Joyent Inc., All rights reserved.

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

# set disable_iptables_flag to the string TRUE 
# to disable iptables service 
disable_iptables_flag=$($MDATA_GET_BIN disable_iptables_flag 2>>/dev/console)

IPF=/sbin/ipf


if [ "$disable_iptables_flag" = "TRUE" -o "$disable_iptables_flag" = "true" -o "$disable_iptables_flag" = "True" ]; then     
   lib_smartdc_info "Metadata field disable_iptables_flag set to - $disable_iptables_flag"

   ipfstat 2>&1 /dev/null 
   if [[ $? -ne 255 ]] ; then 
      lib_smartdc_info "Disabling IPFILTER (IPF) Firewall"
      $IPF -Fa 
      $IPF -D 
   fi

fi

exit 0
