#! /usr/local/bin/bash

# Copyright 2013, Joyent Inc. All rights reserved
# formats the FreeeBSD secondary disk ( /dev/ada1p1 )
# also refered to as the /data disk

# customers can provision this disk how they like
# by default we provision the whole disk as one partition

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

DATADISKDEVICE='ada1'
GPART=`which gpart 2> /dev/null`

checkformount() {
   fstest=$(df -h | grep "/dev/${DATADISKDEVICE}p1")
   if [ -n "$fstest" ] ; then
     fssize=$(echo $fstest | sed 's/[[:space:]]\{2,\}/ /g' | cut -d ' ' -f2)
     lib_smartdc_info "$fssize data disk is mounted on /dev/${DATADISKDEVICE}p1"
     return 1
   else
     lib_smartdc_info "no data disk is mounted on /dev/${DATADISKDEVICE}p1"
     return 0
   fi
}

# Start of Main

lib_smartdc_info "Start of script for FreeBSD"

# check for device
if [[ ! -e /dev/${DATADISKDEVICE} ]] ; then
  lib_smartdc_fatal "secondary disk '/dev/${DATADISKDEVICE}' not found. exiting."
fi

if [[ -z $GPART ]] ; then
  lib_smartdc_fatal "gpart binary not found. exiting."
fi

## Sanity check
checkformount
return_val=$?
if [ "$return_val" -eq 1 ]; then
  lib_smartdc_fatal "data disk is already mounted"
else 
  lib_smartdc_info "no data disk is mounted"
fi

## make sure that a partiton does not already exist
## we do not want to delete any data
partexists=$($GPART show /dev/${DATADISKDEVICE} | grep "1  freebsd-ufs" | wc -l | tr -d ' ')
if [[ $partexists -ne 0 ]] ; then
    lib_smartdc_fatal "Data disk partition '/dev/${DATADISKDEVICE}p1' found. Exiting to prevent deleting data. You will have to format data disk partition manually."
    exit 0;
fi

## create the data disk

# making partition table
lib_smartdc_info "creating gpt partition type /dev/${DATADISKDEVICE}"
gpart create -s gpt $DATADISKDEVICE

DISKSIZE=$(gpart show /dev/${DATADISKDEVICE} | grep free | cut -d'-' -f3 | cut -d'(' -f2 | cut -d')' -f1)

lib_smartdc_info "disksize is $DISKSIZE on $DATADISKDEVICE"

lib_smartdc_info "creating partition /dev/${DATADISKDEVICE}"

# need this sleep to let partition table to update
# if not then /dev/vdb1 will not exist
lib_smartdc_info "sleeping for update of partition table for /dev/${DATADISKDEVICE}"
sleep 2

# creating a single partition for the whole disk, formatting it, and mounting it
gpart add -t freebsd-ufs ${DATADISKDEVICE} 

if [[ -e /dev/${DATADISKDEVICE}p1 ]] ; then
   lib_smartdc_info "creating new filesystem on /dev/${DATADISKDEVICE}p1"
   newfs -L DATA /dev/${DATADISKDEVICE}p1
else
   lib_smartdc_fatal "did not create filesystem on /dev/${DATADISKDEVICE}p1"
fi

# Check for /data and make it
if [[ ! -e /data ]]; then
    lib_smartdc_info "making /data dir mount point"
    mkdir /data
fi

# add entry to fstab so data disk is mounted on reboot
fsentry=$(grep "/dev/${DATADISKDEVICE}p1" /etc/fstab | wc -l | tr -d ' ')
echo "-- $fsentry --"
if [[ $fsentry -eq 0 ]] ; then
  lib_smartdc_info "adding fstab entry for /dev/${DATADISKDEVICE}p1"
  printf "/dev/${DATADISKDEVICE}p1\t/data\t\tufs\trw\t2\t2\n" >> /etc/fstab
else
  lib_smartdc_info "not adding as fstab entry already exist for /dev/${DATADISKDEVICE}p1"
fi

# mount the data disk
lib_smartdc_info "mounting /dev/${DATADISKDEVICE}p1 as /data"
$MOUNT_BIN /data

checkformount
return_val=$?
if [ "$return_val" -eq 1 ]; then
  lib_smartdc_info "data disk is mounted"
else 
  lib_smartdc_fatal "no data disk is mounted"
fi

lib_smartdc_info "End of script"

exit 0
