#!/usr/local/bin/bash
#
# Copyright (c) 2013 Joyent Inc., All rights reserved.
#
# joyent_motd_footer  - write the Joyent footer to the MOTD
# 
# The Joyent MOTD does the following:
#   - gets dataset information

# load common functions and vars
. /lib/smartdc/lib_smartdc_scripts.cfg

# sub that prints dataset info
print_dataset_info() {

   LD=`grep -w bsd_distro $JOYENT_VERSION_FILE | cut -d: -f2 | tr -d ' ' | tr -d '\n' 2> /dev/null`
   LDV=`grep -w bsd_distro_version $JOYENT_VERSION_FILE | cut -d: -f2 | tr -d ' ' | tr -d '\n' 2> /dev/null`
   LDC=`grep -w bsd_distro_name $JOYENT_VERSION_FILE | cut -d: -f2 | tr -d ' ' | tr -d '\n' 2> /dev/null`
   JDV=`grep -w joyent_dataset_version $JOYENT_VERSION_FILE | cut -d: -f2 | tr -d ' ' | tr -d '\n' 2> /dev/null`
   CDC=`grep -w custom_dataset_customer $JOYENT_VERSION_FILE | cut -d: -f2 | tr -d ' ' | tr -d '\n' 2> /dev/null`
   CDT=`grep -w custom_dataset_type $JOYENT_VERSION_FILE | cut -d: -f2 | tr -d ' ' | tr -d '\n' 2> /dev/null`
   CDV=`grep -w custom_dataset_version $JOYENT_VERSION_FILE | cut -d: -f2 | tr -d ' ' | tr -d '\n' 2> /dev/null`
   KV=`$UNAME_BIN -r | tr -d '\n' 2> /dev/null`
   JPN=`grep -w Name $JOYENT_PRODUCT_FILE | cut -d: -f2-3 | sed 's/joyent//gI' | tr -d ' ' | tr -d '\n' 2> /dev/null`
   DOC_URL=`grep -w Documentation $JOYENT_PRODUCT_FILE | cut -d: -f2-3 | tr -d ' ' | tr -d '\n' 2> /dev/null`

   echo "   __        .                   ."
   echo " _|  |_      | .-. .  . .-. :--. |-"
   echo "|_    _|     ;|   ||  |(.-' |  | |"
   echo "  |__|   \`--'  \`-' \`;-| \`-' '  ' \`-'"
   echo "                   /  ;  $JPN ($LD ${LDV} ${JDV})" 
   echo "                   \`-'   $DOC_URL"
   echo "                         $CDC $CDT $CDV"
}


# Start of Main

print_dataset_info
